[package]
authors = ["Jorge Aparicio <jorge@japaric.io>", "Philipp Oppermann <dev@phil-opp.com>"]
build = "build.rs"
categories = ["command-line-utilities", "development-tools", "embedded", "os"]
description = "Automatically cross-compiles the sysroot crates core, compiler_builtins, and alloc."
documentation = "https://docs.rs/crate/cargo-xbuild"
keywords = ["cli", "cross", "compilation", "std", "osdev"]
license = "MIT OR Apache-2.0"
name = "cargo-xbuild"
repository = "https://github.com/rust-osdev/cargo-xbuild"
version = "0.4.7"

[lib]
name = "xargo_lib"

[dependencies]
error-chain = "0.7.2"
fs2 = "0.4.1"
libc = "0.2.18"
rustc_version = "0.1.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempdir = "0.3.5"
toml = "0.2.1"
walkdir = "1.0.3"
cargo_metadata = "0.5.5"

[dev-dependencies]
lazy_static = "0.2.8"

[dev-dependencies.parking_lot]
version = "0.3.6"

[features]
dev = []
